const games = [
    {
        name: "The Last of Us",
        sortname: "last of us 1",
        console: 'PS3',
        genre: ['Horror','Survival','Stealth'],
        pegirating: 18,
        releasedate: 20130614,
        available: true,
        recommended: true,
    },
    {
        name: "The Last of Us Remastered",
        sortname: "last of us 1r",
        console: 'PS4',
        genre: ['Horror','Survival','Stealth'],
        pegirating: 18,
        releasedate: 20140729,
        available: true,
        recommended: true,
    },
    {
        name: "The Last of Us Part II",
        sortname: "last of us 2",
        console: 'PS4',
        genre: ['Horror','Survival','Stealth'],
        pegirating: 18,
        releasedate: 20200619,
        available: true,
        recommended: true,
    },
    {
        name: "Lego Star Wars The Skywalker Saga",
        sortname: "lego star wars 5",
        console: 'PS5',
        genre: ['Family','Puzzle','Platforming'],
        pegirating: 7,
        releasedate: 20220405,
        available: true,
        recommended: false,
    },
    {
        name: "Resident Evil 2",
        sortname: "resident evil 2",
        console: 'PS1',
        genre: ['Horror','Puzzle','Survival'],
        pegirating: 18,
        releasedate: 19980121,
        available: true,
        recommended: false,
    },
    {
        name: "Resident Evil 2",
        sortname: "resident evil 2r",
        console: 'PS4',
        genre: ['Horror','Puzzle','Survival'],
        pegirating: 18,
        releasedate: 20190125,
        available: true,
        recommended: true,
    },
];