const games = [
    {
        name: "The Last of Us",
        console: 'PS3',
        genre: ['Horror','Survival','Stealth'],
        pegirating: 18,
        available: true,
        recommended: true,
    },
    {
        name: "The Last of Us Part II",
        console: 'PS4',
        genre: ['Horror','Survival','Stealth'],
        pegirating: 18,
        available: true,
        recommended: true,
    },
    {
        name: "Lego Star Wars The Skywalker Saga",
        console: 'PS5',
        genre: ['Family','Puzzle','Platforming'],
        pegirating: 7,
        available: true,
        recommended: false,
    },
    {
        name: "Resident Evil 2",
        console: 'PS1',
        genre: 'Horror',
        pegirating: 18,
        available: true,
        recommended: false,
    },
    {
        name: "Resident Evil 2",
        console: 'PS4',
        genre: 'Horror',
        pegirating: 18,
        available: true,
        recommended: true,
    },
];